"use client";
import localFont from "next/font/local";
import NavBar from "./components/ui/Navbar";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { WalletProvider } from "./contexts/walletContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/e474bb5167.js"
          crossorigin="anonymous"
        ></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="min-h-screen bg-gray-100">
        <WalletProvider>
          <Toaster position="top-center" />
          {children}
          <NavBar />
        </WalletProvider>
      </body>
    </html>
  );
}
